char* rgcDefaultConnection = "HTTP/1.1 200 OK\n\r"
"Connection: close\n\r\n\r"
"<html>"
"<head>"
"</head>"
"<body>"
"<h1>ESP8266 Configure</h1>"
"<form action=\"\\SUBMIT\" method=\"GET\">"
"<h2>Station</h2>"
"SSID: <input type=\"text\" name=\"ss\" value=\"SSID\"><br>"
"Pass: <input type=\"text\" name=\"sp\" value=\"pass\">"
"<hr />"
"<h2>AP</h2>"
"SSID: <input type=\"text\" name=\"as\" value=\"SSID\"><br>"
"Pass: <input type=\"text\" name=\"ap\" value=\"pass\">"
"<hr /><h2>Output</h2>"
"<input type=radio name=\"m\", value=\"0\"> Midi"
"<input type=radio name=\"m\", value=\"1\"> Neo"
"<hr/><h2>Id</h2>"
"Internal ID: <input type=\"text\" name=\"as\" value=\"identifier\"><br>"
"<hr/>"
"<input type=\"submit\" value=\"Submit\">"
"</form>"
"</body>"
"</html>";