char* rgcDefaultConnection = "HTTP/1.1 200 OK\n\r"
"Connection: close\n\r\n\r"
"<html>"
"<head>"
"</head>"
"<body>"
"<h1>ESP8266 Configure</h1>"
"<form action=\"\\\" method=\"POST\">"
"<h2>Station</h2>"
"SSID: <input type=\"text\" name=\"s0\" value=\"%s\" maxlength=\"64\"><br>"
"Pass: <input type=\"text\" name=\"s1\" value=\"%s\" maxlength=\"64\">"
"<hr />"
"<h2>AP</h2>"
"SSID: <input type=\"text\" name=\"s2\" value=\"%s\" maxlength=\"64\"><br>"
"Pass: <input type=\"text\" name=\"s3\" value=\"%s\" maxlength=\"64\">"
"<hr /><h2>Output</h2>"
"<input type=radio name=\"s4\" value=\"0\" selected=\"True\"> None"
"<input type=radio name=\"s4\" value=\"1\"> Midi"
"<input type=radio name=\"s4\" value=\"2\"> Neo"
"<hr/><h2>Id</h2>"
"Internal ID: <input type=\"text\" name=\"s5\" value=\"%s\" maxlength=\"64\"><br>"
"<hr/>"
"<input type=\"submit\" value=\"Submit\">"
"</form>"
"</body>"
"</html>";